# -*- coding: utf-8 -*-
"""АнализДанных2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8EBtHiUKigWlUC3pTElroDZ4eyS8Bf0

#Лабораторная работа 3
"""

import pandas as pd

COLUMNS = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "income"
]

train_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
test_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test"

train = pd.read_csv(
    train_url,
    names=COLUMNS,
    skipinitialspace=True,
    na_values="?"
)

test = pd.read_csv(
    test_url,
    names=COLUMNS,
    skipinitialspace=True,
    na_values="?",
    comment="|"
)

# В adult.test классы записаны как <=50K. и >50K.
# Убираем точку в конце.
test["income"] = test["income"].str.rstrip(".")

train.to_csv("adult_train.csv", index=False)
test.to_csv("adult_test.csv", index=False)

dataset = pd.concat([train, test], ignore_index=True)

print(train.head(2))
print(test.head(2))

import numpy as np
import pandas as pd
from collections import Counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

class DecisionTree:
    def __init__(self, criterion="information_gain"):
        if criterion not in ("information_gain", "gain_ratio", "gini_index"):
            raise ValueError("Неизвестный критерий")

        self.criterion = criterion
        self.tree = None

    def _entropy(self, counts):
        counts = np.array(counts, dtype=float)
        p = counts / counts.sum()

        return -np.sum(p[p > 0] * np.log2(p[p > 0]))

    def _gini(self, counts):
        counts = np.array(counts, dtype=float)
        p = counts / counts.sum()

        return 1 - np.sum(p ** 2)

    def _score(self, groups):
        groups = np.array(groups)
        sizes = groups.sum(axis=1)
        total = sizes.sum()
        parent = groups.sum(axis=0)

        if self.criterion == "gini_index":
            parent_impurity = self._gini(parent)
            children_impurity = sum((sizes[i] / total) * self._gini(groups[i]) for i in range(len(groups)))

            return parent_impurity - children_impurity

        parent_entropy = self._entropy(parent)
        children_entropy = sum((sizes[i] / total) * self._entropy(groups[i]) for i in range(len(groups)))
        information_gain = parent_entropy - children_entropy

        if self.criterion == "information_gain":
            return information_gain

        split_info = self._entropy(sizes)

        if split_info == 0:
            return 0

        return information_gain / split_info

    def _best_split(self, X, y, features):
        best = None
        best_score = -1

        for feature in features:
            column = X[feature].to_numpy()

            if np.issubdtype(X[feature].dtype, np.number):
                order = np.argsort(column)
                x_sorted = column[order]
                y_sorted = y[order]

                positive = (y_sorted == ">50K").astype(int)
                positive_left = np.cumsum(positive)

                for i in range(len(y) - 1):
                    if x_sorted[i] == x_sorted[i + 1]:
                        continue

                    left_size = i + 1
                    right_size = len(y) - left_size

                    left_positive = positive_left[i]
                    right_positive = positive_left[-1] - left_positive

                    groups = [
                        [left_size - left_positive, left_positive],
                        [right_size - right_positive, right_positive]
                    ]

                    score = self._score(groups)

                    if score > best_score:
                        best_score = score
                        threshold = (x_sorted[i] + x_sorted[i + 1]) / 2
                        best = {"feature": feature, "type": "numeric", "threshold": threshold, "score": score}

            else:
                values = np.unique(column)

                if len(values) <= 1:
                    continue

                groups = []

                for value in values:
                    subset = y[column == value]
                    negative = np.sum(subset == "<=50K")
                    positive = np.sum(subset == ">50K")
                    groups.append([negative, positive])

                score = self._score(groups)

                if score > best_score:
                    best_score = score
                    best = {"feature": feature, "type": "categorical", "score": score}

        return best

    def _build(self, X, y, features):
        positive = np.sum(y == ">50K")
        negative = np.sum(y == "<=50K")
        prediction = ">50K" if positive > negative else "<=50K"

        node = {"prediction": prediction}

        if positive == 0 or negative == 0 or len(features) == 0:
            return node

        split = self._best_split(X, y, features)

        if split is None or split["score"] <= 0:
            return node

        feature = split["feature"]

        node["feature"] = feature
        node["type"] = split["type"]

        if split["type"] == "numeric":
            threshold = split["threshold"]
            mask = X[feature].to_numpy() <= threshold

            node["threshold"] = threshold
            node["left"] = self._build(X[mask], y[mask], features)
            node["right"] = self._build(X[~mask], y[~mask], features)

        else:
            node["children"] = {}
            new_features = [f for f in features if f != feature]

            for value in X[feature].unique():
                mask = X[feature].to_numpy() == value
                node["children"][value] = self._build(X[mask], y[mask], new_features)

        return node

    def fit(self, X, y):
        self.tree = self._build(X.reset_index(drop=True), np.array(y), list(X.columns))

    def _predict_one(self, row, node):
        if "feature" not in node:
            return node["prediction"]

        feature = node["feature"]

        if node["type"] == "numeric":
            if row[feature] <= node["threshold"]:
                return self._predict_one(row, node["left"])

            return self._predict_one(row, node["right"])

        value = row[feature]

        if value not in node["children"]:
            return node["prediction"]

        return self._predict_one(row, node["children"][value])

    def predict(self, X):
        return np.array([self._predict_one(row, self.tree) for _, row in X.iterrows()])


def classify(train, test, criterion="information_gain", train_fraction=1.0):
    if not 0 < train_fraction <= 1:
        raise ValueError("train_fraction должен быть от 0 до 1")

    if train_fraction < 1:
        train = train.sample(frac=train_fraction, random_state=42)

    train = train.fillna("?")
    test = test.fillna("?")

    X_train = train.drop(columns="income")
    y_train = train["income"]

    X_test = test.drop(columns="income")
    y_test = test["income"]

    model = DecisionTree(criterion)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    results = {
        "Accuracy (аккуратность):": accuracy_score(y_test, y_pred),
        "Precision (точность):": precision_score(y_test, y_pred, pos_label=">50K", zero_division=0),
        "Recall (полнота):": recall_score(y_test, y_pred, pos_label=">50K", zero_division=0),
        "F-мера:": f1_score(y_test, y_pred, pos_label=">50K", zero_division=0)
    }

    return model, results

model, results = classify(train, test, criterion="information_gain", train_fraction=1.0)
print(results)

model_ig, results_ig = classify(train, test, criterion="information_gain", train_fraction=1.0)
print("Information Gain:", results_ig)

model_gr, results_gr = classify(train, test, criterion="gain_ratio", train_fraction=1.0)
print("Gain Ratio:", results_gr)

model_gini, results_gini = classify(train, test, criterion="gini_index", train_fraction=1.0)
print("Gini Index:", results_gini)

"""##Визуализация"""

import matplotlib.pyplot as plt

def is_leaf(node):
    return "feature" not in node


def draw_limited_tree(ax, node, x, y, dx, level, max_depth):
    if level > max_depth:
        ax.text(x, y, "...", ha="center", va="center", bbox=dict(boxstyle="round", fc="white"))
        return

    if is_leaf(node):
        ax.text(x, y, node["prediction"], ha="center", va="center", bbox=dict(boxstyle="round", fc="lightgreen"))
        return

    if node["type"] == "numeric":
        label = f'{node["feature"]}\n<= {node["threshold"]:.2f}'
        ax.text(x, y, label, ha="center", va="center", bbox=dict(boxstyle="round", fc="lightblue"))

        child_y = y - 2
        left_x = x - dx
        right_x = x + dx

        ax.plot([x, left_x], [y, child_y], "k-")
        ax.plot([x, right_x], [y, child_y], "k-")

        ax.text((x + left_x) / 2, (y + child_y) / 2, "<=", ha="center", va="center")
        ax.text((x + right_x) / 2, (y + child_y) / 2, ">", ha="center", va="center")

        draw_limited_tree(ax, node["left"], left_x, child_y, dx / 1.8, level + 1, max_depth)
        draw_limited_tree(ax, node["right"], right_x, child_y, dx / 1.8, level + 1, max_depth)

    else:
        ax.text(x, y, node["feature"], ha="center", va="center", bbox=dict(boxstyle="round", fc="lightblue"))

        children = list(node["children"].items())
        n = len(children)
        child_y = y - 2

        for i, (value, child) in enumerate(children):
            child_x = x + (i - (n - 1) / 2) * dx
            ax.plot([x, child_x], [y, child_y], "k-")
            ax.text((x + child_x) / 2, (y + child_y) / 2, str(value), ha="center", va="center")
            draw_limited_tree(ax, child, child_x, child_y, dx / max(n, 2), level + 1, max_depth)


def visualize_tree(model, title, max_depth=5):
    plt.figure(figsize=(20, 10))
    ax = plt.gca()
    ax.set_title(title)
    ax.axis("off")

    draw_limited_tree(ax, model.tree, x=0, y=0, dx=8, level=1, max_depth=max_depth)

    plt.show()

visualize_tree(model_ig, "Decision Tree - Information Gain", max_depth=2)
visualize_tree(model_gr, "Decision Tree - Gain Ratio", max_depth=2)
visualize_tree(model_gini, "Decision Tree - Gini Index", max_depth=2)

from sklearn.model_selection import train_test_split

criterion = "gain_ratio"
fractions = [0.6, 0.7, 0.8, 0.9]

experiment_results = []

for fraction in fractions:
    train_part, test_part = train_test_split(dataset, train_size=fraction, random_state=42, stratify=dataset["income"])

    model, results = classify(train_part, test_part, criterion=criterion, train_fraction=1.0)

    experiment_results.append({
        "train_fraction": fraction,
        "test_fraction": 1 - fraction,
        "accuracy": results["Accuracy (аккуратность):"],
        "precision": results["Precision (точность):"],
        "recall": results["Recall (полнота):"],
        "f1": results["F-мера:"]
    })

    print(f"{int(fraction * 100)}:{int((1 - fraction) * 100)}", results)


results_df = pd.DataFrame(experiment_results)
print(results_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.plot(results_df["train_fraction"] * 100, results_df["accuracy"], marker="o", label="Accuracy")
plt.plot(results_df["train_fraction"] * 100, results_df["precision"], marker="o", label="Precision")
plt.plot(results_df["train_fraction"] * 100, results_df["recall"], marker="o", label="Recall")
plt.plot(results_df["train_fraction"] * 100, results_df["f1"], marker="o", label="F-мера")

plt.xlabel("Доля обучающей выборки, %")
plt.ylabel("Значение метрики")
plt.title("Зависимость качества классификации от размера обучающей выборки")

plt.xticks([60, 70, 80, 90])
plt.ylim(0.60, 0.84)

plt.legend()
plt.grid()

plt.show()